name: fault-lstm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow>=2.12
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - ipywidgets
      - seaborn
      - setuptools
